version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./pois_with_wikidata.csv:/data/pois_with_wikidata.csv:ro
      - ./poi_distances.csv:/data/poi_distances.csv:ro
      - ./.env:/app/.env:ro
    environment:
      - ENVIRONMENT=prod
